repos:
  # Built-in basic fixes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer          # ensure newline at EOF
        files: ^docs/src/.*\.md$
      - id: trailing-whitespace        # strip trailing spaces
        files: ^docs/src/.*\.md$

  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        name: markdownlint (md)
        entry: markdownlint
        language: node
        types: [file]
        files: ^docs/src/.*\.md$
        exclude: ^docs/src/developer/manual/
        args: [--fix]

  - repo: local
    hooks:
      - id: mkdocs-build
        name: mkdocs build
        entry: mkdocs build --config-file docs/mkdocs.yml
        language: system
        files: ^docs/src/
        pass_filenames: false
        always_run: true

  # Check for broken links in Markdown files
  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.13.7
    hooks:
      - id: markdown-link-check
        name: markdown-link-check (link sanity)
        entry: markdown-link-check
        language: node
        files: ^docs/src/.*\.md$
        args: ["--quiet"]
